### ISSUE TITLE
List of small UI bugs to resolve

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#166]
Collecting some UI bugs which we should address, potentially breaking them up into sub-issues for solving one by one. If you'd like to repost one individually, please link it from here with a comment, thanks!

* [x] 2 clicks required to show toolbar (should be just one)
* [x] clicking away from an image (onto background) doesn't deselect it
* [x] placement of toolbar should be at position of mouse click

For these three issues, see the gif here for a demonstration: 

![mapknitter](https://user-images.githubusercontent.com/24359/54284762-eca1e080-4576-11e9-85b0-8a870fecaea7.gif)

Thanks!!!

**Comment by sashadev-sky** [comment]
@jywarren only one more to go here!

Please see first two below (this fixes are all in my multiple image select PR):

![bug7](https://user-images.githubusercontent.com/41092741/54620318-5ec56a00-4a3c-11e9-9963-fb526bfacd92.gif)

**Comment by jywarren** [comment]
oh wow!!!!

**Comment by sashadev-sky** [comment]
@jywarren for this third point, do you think it would be better to just apply some CSS positioning (relative for images absolute for toolbars) or find another implementation? With mouse click the toolbar would end up on top of the image and whereever else

**Comment by jywarren** [comment]
I think css positioning would be great. I just think there are a couple
scenarios, one where the top of the image is off screen, so it's hidden
that way, and perhaps a few other edge cases...

**Comment by sashadev-sky** [comment]
Yeah that is the one reason I am hesitant about it, this type of implementation can get hacky but I will look into it

**Comment by sashadev-sky** [comment]
since I was already on mapknitter i just wanted to post documentation of the some current toolbar issues that I will be solving in a new PR (will link it back here)
1) possibility of toolbar overlapping with the handles making them impossible to grab. 
2) The current implementation also relies on the image's position (which is unstable) and explains the instability in toolbar position that has been reported before. 
3) Zoom levels are not accounted for so if you click on the image to trigger the toolbar to show from a higher zoom level, by the time you zoom back in to the default (13), the toolbar will be out of view
4) Dragged corners are ignored which is another possible way for the toolbar to position itself blocking a corner

This just shows point 1:
![toolbar-bug-mapknit](https://user-images.githubusercontent.com/41092741/55768440-eeae7080-5a4a-11e9-925e-f311e2023f91.gif)

**Comment by Greg-Tarr** [comment]
@sashadev-sky 

Hello, 

You mentioned that dragged corners are ignored by the toolbar and overlapping.

I fixed this issue: #210 

It makes sure no overlapping is possible.

Thanks.

**Comment by sashadev-sky** [comment]
final point checked off and this is now closed via #210
