### ISSUE TITLE
Add documentation for img._addTool()

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#194]
After https://github.com/publiclab/Leaflet.DistortableImage/pull/149/, we now have the ability to add a new tool to the popup toolbar at runtime. The syntax is:

```js
img._addTool(NewTool)
```

And a tool looks like this: 

https://github.com/publiclab/Leaflet.DistortableImage/blob/0a9f23240a1703a9ee11e5ec743997faba842a1f/src/edit/DistortableImage.EditToolbar.js#L12-L25

However, in the demo, i can't seem to use `img._addTool(RemoveOverlay);` to add another instance of the `RemoveOverlay` tool. Maybe I'm using it wrong? 

In any case, much of this is run from this file: https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/DistortableImage.EditToolbar.js

We should add some documentation and tests! This is a really nice new feature by @rexagod, and will help us potentially manage the growing # of new tools better, allowing very customized tools to live in downstream repositories instead of within this core library.

**Comment by rexagod** [comment]
@jywarren `img._addTool(RemoveOverlay)` or generally adding any of the "inbuilt" actions won't work because what I had in mind was adding an "extra" functionality, i.e., an **external** action that user can define in the `html` script tags and associate that with the image straightaway, and therefore, I didn't link this with any of the inbuilt actions present in `EditToolbar.js`. I never considered a scenario of adding an inbuilt functionality this way because I wasn't unable see a usage for that. But nonetheless, I can incorporate this feature (of including inbuilt fn. as well) if you want to and see a usage that I might have failed to. Also, as far as the testing goes, we can definitely add some tests I had in mind. What do you think?

**Comment by sashadev-sky** [comment]
@jywarren @rexagod I am going to close this one! But noting we still need to document adding a custom external action (what @rexagod is referring to above) - this is now possible, but I think we should hold off on this until we finish figuring out how to implement it as an easy to use API as well (#317)
