### ISSUE TITLE
Image distorted in Scale mode

### ISSUE THREAD

**Issue by flopail** [publiclab/Leaflet.DistortableImage#301]
**Describe the bug:**
When scale mode is active, image is sometimes distorted (so initial ratio is lost). There is a quite similar issue #85, but this one is closed and bug seems to be still there.

**Reproduce the behavior:**
To reproduce this bug, do a mousedown on a corner and resize image at min, then extend it (several times if necessary). Please see gif below.
![Scale-bug](https://user-images.githubusercontent.com/32390593/59091900-9bed1a00-8910-11e9-9752-dd9177c899fb.gif)

**Browser, version, and operating system:**
- Leaflet.DistortableImage v0.4.2
 - Firefox 67.0, Chrome 74.0
- Windows 10 (64bits)

**Comment by jywarren** [comment]
Oh thank you, and such good documentation of the issue as well!!!!

**Comment by jywarren** [comment]
This is probably slow drift from the continuous recalculation from the
previous location. Could be floating point drift? Or something like that?

In any case we could preserve the original aspect ratio when in this non
distortion mode maybe?

**Comment by sashadev-sky** [comment]
@flopail the solution I think will correct this is outlined here: https://github.com/publiclab/Leaflet.DistortableImage/issues/219 - but the problem with it is those numbers are hardcoded based on my own trial and error for a specific image size. (I also moved those properties inside the class and have not documented them as part of the API yet because of aforementioned hardcoding). They were better than nothing, though, because they prevented an error where scaling down enough deleted the image and extreme distortions.

If you wanted to take a shot at it I would love your help!! 

Returning to original aspect ratio also seems like a reasonable solution although the first one would be less of a workaround. But, it could also be the most plausible solution! I have already started on a restore function #274 so it could be something extending that.

**Comment by sashadev-sky** [comment]
Reopening #85 . Also noting we never implemented any solution for pure scale, just rotateScale.

**Comment by jywarren** [comment]
In looking into #340, I think this is the responsible section for at least some of the distortions: 

https://github.com/publiclab/Leaflet.DistortableImage/blob/70b22a2ff4e5b7f0c939ea70340746bbade161cc/src/edit/DistortableImage.Edit.js#L244-L251

I think it's because the values we're using to scale are integers and so we lose decimal precision over time as you keep running this math. 

But maybe it's more complex as well: looking at @flopail's docs and testing myself, all images will tend to become square over time. I don't know if this makes sense re: the decimal precision issue. 

But there may be a second reason for distortion. I noticed I was able to get images to turn from this:

![image](https://user-images.githubusercontent.com/24359/61010301-b2d5c080-a343-11e9-8f46-38b2a4b6a2e3.png)


to this:

![image](https://user-images.githubusercontent.com/24359/61010290-acdfdf80-a343-11e9-87ca-010a5e7ed2c5.png)

And I'm not sure why! That's certainly not square.

**Comment by jywarren** [comment]
Here's an animation of this 2nd type. I don't know if finding a solution to the decimal precision section would solve this too?

![mapknitter](https://user-images.githubusercontent.com/24359/61010497-7c4c7580-a344-11e9-8440-26c3a5543687.gif)

**Comment by jywarren** [comment]
Maybe we could do all the math in latitude/longitude instead of pixels, but that could introduce some strange behavior if lat and lon aren't the same scale -- like, in current math we go to the origin (add and subtract `center`) i think... not sure if that'd work...

Maybe this could help? https://github.com/bbecquet/Leaflet.PolylineDecorator/commit/00f7db59fe322852b0b72cc70ca37fc3d79087ce

**Comment by jywarren** [comment]
There they use `map.project()` instead of `map.latLngToLayerPoint()`... let me try.

**Comment by jywarren** [comment]
https://leafletjs.com/reference-1.4.0.html#projection

**Comment by jywarren** [comment]
Whoa! uh... maybe I solved the trapezoidal distortion issue with this, but not the tending-towards-squareness type?

**Comment by jywarren** [comment]
See #341!

**Comment by jywarren** [comment]
Hmm. OK, it's even possible there's a third type:

![image](https://user-images.githubusercontent.com/24359/61010968-5de77980-a346-11e9-918a-7956bcf9311a.png)

**Comment by jywarren** [comment]
By increasing the minimum size you can make an image in https://github.com/publiclab/Leaflet.DistortableImage/pull/340/ (set there to 50) we may be able to limit this because the rounding errors may be more dramatic at smaller pixel sizes (since the errors are larger proportionally to the image size). 

Another approach could be to essentially remember all corner coordinates (measured as x, y from the image center, perhaps) upon `mousedown`, and no matter what, `scaleBy()` and other functions would reproject those original values transformed by a scale and rotation. This would ensure that it preserves the same proportions/shape no matter what. I guess I really think this is the true solution here. That would mean that in the `_onHandleDrag()` event handler here:

https://github.com/publiclab/Leaflet.DistortableImage/blob/70b22a2ff4e5b7f0c939ea70340746bbade161cc/src/edit/RotateScaleHandle.js#L11-L37

...we'd record original positions in `x,y` (relative to image center?) on `_onHandleDragStart()`, and then in `_onHandleDrag()` we'd update using those originally stored values.

**Comment by jywarren** [comment]
However, #341's use of `project()` instead of `latLngToLayerPoint()` is also important, so as to preserve decimal precision!

**Comment by sashadev-sky** [comment]
@jywarren keeping track of proportions and then setting the image back to them is basically what I implemented for the "Restore" action! But I think its not perfect either, it applies a slight translation. Haven't looked into that yet.

I managed to get it working via Matrix math with no distortions in #339 ! I would love some feedback there - its far from done yet - I still have to figure out how to make the markers update too and it currently works best with "img2" which didn't get initial corners assigned to it.

**Comment by sashadev-sky** [comment]
@flopail I believe this is fixed for version 0.7.0 now! Please reopen if you find this to not be the case

**Comment by sashadev-sky** [comment]
@jywarren it turns out switching to `project` and standardizing our calls to reset & update did the trick. Still a little confused because `latLngToLayerPoint` is not relative to absolute pixel coords and `project` is so I thought this was the reason. but also, not documented anywhere, `project` does have extra decimal precision (uses 9 digits - I just checked in console). But why have two core API methods, with one that is imprecise and not document that if it causes visible distortions? Looking at the source code is even more confusing, bc `layerPointToLatLng` returns the same precision as `project` and `unproject`, but `latLngToLayerPoint` uses `round()`, which strips all decimal precision to return an Integer, not sure why that would be desired

![image](https://user-images.githubusercontent.com/41092741/62911312-ea27fa80-bd51-11e9-9805-68aebccaa5c6.png)

Sorry I just want to get this down as it'll continue being relevant still
