### ISSUE TITLE
Breaking change to toggleRotateDistort?

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#319]
I realize the change from `_toggleRotateDistort` to `_toggleRotateScale` in https://github.com/publiclab/Leaflet.DistortableImage/pull/229/files#diff-768de6f5429b5761052f2e8e3640ec12R73 could be considered a breaking change -- it definitely needs refactoring in https://github.com/publiclab/mapknitter/pull/782. 

Should we bump LDI a major version number as a result? Or add an adapter/alias to make it backwards compatible for now until we eventually do make an API-breaking version number update?

**Comment by jywarren** [comment]
cc @sashadev-sky what do you think?

**Comment by sashadev-sky** [comment]
@jywarren whatever you think! I had thought because we hadn't revealed that to the outer API as `_toggleRotateDistort` its not considered a breaking change because the expectation is that people weren't grabbing that method from the source code anyway?

I read that until version 1 of a package is released, you don't strictly have to follow semver convention. but once version 1 is you do. So I have been holding off on major version bump because I am still doing a bit of restructuring esp for #161

**Comment by jywarren** [comment]
Sounds good. Let's alert @ChrisLowe-Takor about this just in case it affects that downstream usage. Thanks!

**Comment by jywarren** [comment]
linking to https://github.com/publiclab/Leaflet.DistortableImage/issues/105

**Comment by ChrisLowe-Takor** [comment]
No won't effect me - I'm still using the local hacked up version in the react wrapper.  Honestly, that repo has gotten a little stale and I won't have the time to update for at least a few months so don't worry about any breaking changes on my part.

**Comment by sashadev-sky** [comment]
closing this one now as its resolved!
