### ISSUE TITLE
Add border tool bound to "delete" action - bug?

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#343]
I clicked the border button but got this notice -- maybe a small crossed wiring of these? Not a huge deal since there's a confirm alert but we should try to patch this pretty quick. Thanks!

![image](https://user-images.githubusercontent.com/24359/61064323-8d8e9400-a3cf-11e9-85a4-4b3488a3e572.png)

**Comment by sashadev-sky** [comment]
Weird! I think this must be a MK issue? I did a quick lookover and I don't see any glaring mistakes there. Will try to look into it this weekend

**Comment by sashadev-sky** [comment]
So I don't see any crosswiring directly (from the action code in MK) so it must be happening somewhere underneath. 

Noting that clicking the `delete` button results in this:
![image](https://user-images.githubusercontent.com/41092741/61336393-29206a00-a7ff-11e9-8ecb-4091dddc0531.png)

While `border_outline` results in this:
![image](https://user-images.githubusercontent.com/41092741/61336438-4a815600-a7ff-11e9-99eb-4b0ded23b67d.png)

Is this the case for you too? Your snapshot is showing otherwise

**Comment by sashadev-sky** [comment]
Adding that the `toggleOutline` keybinding (`o`) still works as normal

**Comment by sashadev-sky** [comment]
It's firing because when we toggle an outline, we remake the toolbar (should probably fix this so thats not the case at some point) which then fires 

https://github.com/publiclab/mapknitter/blob/7954bf153540162845fbdf6f9e6c17a829e6512b/app/assets/javascripts/mapknitter/Map.js#L230-L245

@jywarren I don't really understand the relationship of creating a toolbar to deleting written in the code above. ie.
```
img.on('toolbar:created',
      function () {
        this.editing.toolbar.options.actions[1].prototype.addHooks = function () {
          var map = this._map;
          this._overlay.fire('delete');
        }
      }, img)
```
