### ISSUE TITLE
Option to change strings

### ISSUE THREAD

**Issue by adriankwiat** [publiclab/Leaflet.DistortableImage#406]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

**Please describe the desired behavior.**
Describe the solution you'd like.

I'm making an app in another language and I want to change default strings (tooltips, confirms, etc).

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

For example:
```javascript
let img = L.distortableImageOverlay('image.jpg', {
  // options
  strings: {
    delete: 'Usuń',
    confirmDelete: 'Czy na pewno chcesz usunąć obraz?',
    lock: 'Zablokuj',
    unlock: 'Odblokuj',
    rotate: 'Obróć',
    // ...
  }
});
```

**Comment by sashadev-sky** [comment]
Hi! Thank you for the feature request. We are in the process of revamping our actions API to make each action customizable without have to overwrite the whole thing. This will probably be done in the next few weeks or so. 

In the meantime, you can achieve your desired results by rewriting the actions as custom actions. This is not well documented in the README currently because there will be updates - 

To create a custom action, just extend `L.EditAction`. 

Here is an example of one we overrwrote downstream (this is done for the collection group, but `L.distortableImageOverlay` takes the same `actions` option.

```JS
 var customDeletes = mapknitter.customDeletesAction();
 var imgGroup = L.distortableCollection({
     actions: [customExports]
  }).addTo(map);

 /** The upstream delete action also triggers a confirmation window, this one won't */
  customDeleteAction: function () {
    var action = L.EditAction.extend({
      initialize: function (map, overlay, options) {
        var use = 'delete_forever';
        options = options || {};
        options.toolbarIcon = {
          svg: true,
          html: use,
          tooltip: 'Delete Image'
        };

        L.EditAction.prototype.initialize.call(this, map, overlay, options);
      },

      addHooks: function () {
        this._overlay.fire('delete');
      }
   });

   return action;
}
```

It is not ideal, because you would have to recreate every action, but it is the way you would do this before we expand our API for it.

Let me know if you have any more questions!

**Comment by rexagod** [comment]
Uploaded to GCI dashboard.

**Comment by SidharthBansal** [comment]
Please read through the guidelines of gci tasks creation. You are missing scores, code links and adding it to the tasklist.
Thanks

**Comment by SidharthBansal** [comment]
Similarly for other issues/tasks
