### ISSUE TITLE
odd/wild distortions on zooming in Firefox

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#42]
sometimes only minor (~30%?) changes in corner positions, briefly during zooming, and sometimes radical distortions as corners get moved off screen during zooms. This does not happen in Safari or Chrome on Mac, but does on Firefox 35 for Mac and Ubuntu and Firefox for Android.

![screen shot 2015-02-05 at 12 43 52 pm](https://cloud.githubusercontent.com/assets/24359/6065650/012afdc2-ad35-11e4-9e30-e09a39a8676a.png)

Should be (note probably unrelated partial-load issues as reported in https://github.com/publiclab/mapknitter/issues/83):

![screen shot 2015-02-05 at 12 43 51 pm](https://cloud.githubusercontent.com/assets/24359/6065653/05611bec-ad35-11e4-9637-76c68f4da9e4.png)

**Comment by jywarren** [comment]
Perhaps for now, we ought to disable zoom animations in FF?

**Comment by jywarren** [comment]
Further exploration shows that this seems to only happen when the image is actually non-rectangularly distorted, i.e. if it's a rectangle, it animates correctly. [Try this example](http://publiclab.github.io/Leaflet.DistortableImage/examples/index.html) as-is, then move one corner and repeat zooming in/out.

The transform used in image._animateZoom is: `matrix3d(-0.23301688888890204,0,0,0,0,0.24959845435433092,0,0,0,0,1,0,0,0,0,1)` if that makes any difference at all.

**Comment by jywarren** [comment]
If this is a precision issue, this post includes a discussion and possible solution for the precision issues, but I don't know if that maps to our problem; they discussed only jerkiness (aliasing). http://greensock.com/forums/topic/11115-css3-rotation-and-matrix3d-values-precision-vs-the-straight-rotatey/

**Comment by jywarren** [comment]
I'm going to disable animations in FF until we resolve this issue.

**Comment by btbonval** [comment]
I don't think the matrix math is the problem, since the matrix math works fine in Chrome. What I see in my screen is the bottom two points being thrown somewhere off screen while the top two points remain the same. 

If the problem was a precision error, I would think you should be able to zoom out far enough that you can see the image being mapped within some error radius of the precision. If I zoom all the way out to the whole world, the image still goes bonkers over the entire map.

The real problem appears to be how transitions are handled by Firefox (since disabling them fixed it), or maybe how the browsers work with Leaflet itself.
