### ISSUE TITLE
show both rotate and distort buttons, and disable/grey out the one currently active

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#44]
This relates to #27; we'd then only have to change the icon (color) and not the function when switching.

**Comment by jywarren** [comment]
to change the icon, access: `image.editing.toolbar.options.actions[1].prototype.options.toolbarIcon`

**Comment by rexagod** [comment]
@jywarren Is this still under consideration? We already have a functionality that alternates between the two,  but I'd like to hear your thoughts on this. Thanks!

**Comment by sashadev-sky** [comment]
@jywarren @rexagod just saw this and wondering the same thing. I don't think it makes sense to gray them out anymore because they are not the only two actions. In that case, we would be graying out everything but the button selected (or the inverse - showing the selected button as selected by making it black or something along those lines). I brought that up in #238.

So would suggest to close this one or this is still more to be done here?

**Comment by jywarren** [comment]
Yeah, i think let's close it for now. Thanks!
