### ISSUE TITLE
if zoom before selecting an image in Firefox Mac, toolbar becomes unresponsive

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#53]
in FF 39.0 and Firefox 37.0.2 in http://mapknitter.org/maps/katamon-2

**Comment by jywarren** [comment]
@fiestin reports a similar issue on Firefox 40.0.3 - and had reported on previous versions that restarting firefox helped (which is odd), but that no longer resolves the issue, and she reports also "unresponsive scripts and slow performance" in Firefox 40.0.3 on Mac. 

However I'm not sure this is the same issue - as @fiestin says zooming doesn't work at all.

My tests had previously shown that in Firefox 37.0.2 images are unresponsive **if the first thing you do is zoom**. But if you click on an image first (just after the page loads) and **then** zoom, it is OK.

@fiestin, can you try this last test, to see if clicking on an image first suppresses this bug? Thanks for reporting!

**Comment by fiestin** [comment]
Yes, it works if I click on an image before zooming. and I can drag the map sideways. thanks!

**Comment by gauravano** [comment]
@publiclab testing for the mention, please ignore and sorry for the inconvenience.

**Comment by sashadev-sky** [comment]
@jywarren I was looking back at this issue and the latest version of Firefox Mac is now 66.0.2, where this issue does not happen. Does that mean this issue is resolved or what is convention for a scenario like this?

**see below: in both scenarios I refresh the page before anything else:**
(there is another zoom issue now with the image separating from the handles apparently that would be a separate issue to open - considering maybe looking through leaflet updates to see if it has been addressed anywhere since we are a few versions behind there)

![firefox-test](https://user-images.githubusercontent.com/41092741/55526923-f34ae180-5664-11e9-8c1c-48ba4127ad98.gif)


confirming its the same case on mapknitter. Toolbar and image is responsive:
![firefox-test2](https://user-images.githubusercontent.com/41092741/55527328-918b7700-5666-11e9-85a5-152b88858159.gif)

**Comment by sashadev-sky** [comment]
@jywarren also here is the map dragged sideways:

![firefox-test3](https://user-images.githubusercontent.com/41092741/55527487-458d0200-5667-11e9-9608-7b16442fb0c7.gif)

**Comment by jywarren** [comment]
I think that may mean it's OK then. Want to close this?
