### ISSUE TITLE
Mapknitter in Safari: stitch separates from base layer when dragging

### ISSUE THREAD

**Issue by fiestin** [publiclab/Leaflet.DistortableImage#57]
Safari 8.0.8
when I drag the base layer it separates from the stitched map, both stay in the same zoom level when zoom in and out. When I double click an image for the edit menu it zooms in.
Detailed description: I refresh the page and start by dragging then zoom out, double click an image on the right side of the map and a different image is clicked, the one that is to the left. I click the last one and it zooms in. I click a different one, now it works, I click it again and it doesn't respond. I click the image to the left, and the one to the right is on with the menu. I click it and the one to the left is on. It seems as though clicking has shifted to the left from the position of the mouse. Now everywhere I click on the map it turns on images to the right. 
If I click on images on the left side of the map it zooms in. 
The menu itself doesn't respond. instead it jumps to a different image.
when I try to use the twist/scale handles sometimes it works, sometimes it drags the base layer.
some images appear transparent.
I will file some of these as different issues.

**Comment by jywarren** [comment]
Yes, please break this out into separate issues and if you can provide screenshots that will help us understand what you're seeing. Thank you!!

**Comment by jywarren** [comment]
Ah, i wonder if this is because in some interfaces, double click issues a Leaflet command to zoom in?

**Comment by sashadev-sky** [comment]
hey! This issue is definitely stale by now, as 
1. we have added custom double-click to patch leaflets previously broken doubletap functionality, and 
2. we have updated the formulas we use all over to recalculate the pixel origin on map drag, (While zooming the map automatically does this, dragging it didn't which created a few tough bugs we had to solve)

Last, i cannot reproduce it in safari 8.0.8!

Closing this PR - feel free to open a new one if you are still experiencing these issue :)
